### ISSUE TITLE
Make the address of the Dev Server a clickable link

### ISSUE THREAD

**Issue by khill-fbmc** [inngest/inngest-js#138]
**Is your feature request related to a problem? Please describe.**
It would be nice if the address for the inngest dev server was clickable.

**Describe the solution you'd like**
Wrap the address in an `<a>` tag

**Describe alternatives you've considered**
It seems like a simple feature.

**Additional context**
![image](https://user-images.githubusercontent.com/107003416/225633944-62155a84-436f-4601-a85c-2ef81f79de8c.png)

**Comment by jpwilliams** [comment]
@khill-fbmc Would love a PR for this, aye! This is actually defined in the [inngest/inngest-js](https://github.com/inngest/inngest-js) repo - I've just transferred the issue over.

The code you're looking for sure be over at [`./landing/src/components/DevServerBar.tsx:57`](https://github.com/inngest/inngest-js/blob/main/landing/src/components/DevServerBar.tsx#L57-L62).

**Comment by jpwilliams** [comment]
Closed by #137.
