### ISSUE TITLE
Simplification of defining event types

### ISSUE THREAD

**Issue by khill-fbmc** [inngest/inngest-js#139]
**Is your feature request related to a problem? Please describe.**
I don't like that [in the example on the site](https://www.inngest.com/docs#a-small-but-powerful-example), the event name is repeated 3 times.

**Describe the solution you'd like**
I would love utility types or helper functions to reduce the repetition.

**Describe alternatives you've considered**
I tried making a type as such to reduce the overhead some:
```ts
type InngestNamedEventRecord<T extends { name: string }> = Record<T["name"], T>;
```
That worked fine, defining the event like so:

```ts
export type SendEmailEvent = InngestNamedEventRecord<{
  name: "app/email.send";
  data: {
    mailTo: string;
    subject: string;
    message: string;
  };
}>;
```
You can then `&` merge that type with all the others to reduce the repetition in the main event record provided to the client.

**Comment by jpwilliams** [comment]
Closing this as the method suggested above was added in v2 a while ago. 🥳

Check out [Defining Event Payload Types - Inngest Documentation](https://www.inngest.com/docs/reference/client/create#defining-event-payload-types) to see all the methods available.
