### ISSUE TITLE
Type errors in inngest types and in dependencies

### ISSUE THREAD

**Issue by mahdavipanah** [inngest/inngest-js#150]
**Describe the bug**
Typescript (v4.4.3) gives type errors. The errors are both related to `inngest/types.d.ts` and Inngest's **type-fest** dependency module.

**To Reproduce**

1. Create an instance of `Inngest`:
```typescript
import { Inngest } from "inngest";

const client = new Inngest({ name: "My app" });
```
2. Run `tsc`.

**Expected behavior**
I expected the code to be compiled without any errors.

**Code snippets / Logs / Screenshots**
**Temporarily fix**:
Setting typescript's `skipLibCheck` compiler option to true will solve the problem temporarily as it skips the type checking on imported packages. `tsconfig.json`:
```json.
  ...
  "compilerOptions": {
    "skipLibCheck": true,
  },
  ...
```

**Error logs:**
```sh
node_modules/inngest/node_modules/type-fest/source/camel-case.d.ts:25:32 - error TS1005: '?' expected.

25  infer FirstWord extends string,
                                  ~

node_modules/inngest/node_modules/type-fest/source/camel-case.d.ts:26:42 - error TS1005: '?' expected.

26  ...infer RemainingWords extends string[],
                                            ~

node_modules/inngest/node_modules/type-fest/source/join.d.ts:32:56 - error TS1005: '?' expected.

32    ...infer Rest extends ReadonlyArray<string | number>,
                                                          ~

node_modules/inngest/types.d.ts:137:45 - error TS1005: '>' expected.

137     tools: ReturnType<typeof createStepTools<TEvents, TTrigger>>[0];
                                                ~

node_modules/inngest/types.d.ts:137:64 - error TS1005: '(' expected.

137     tools: ReturnType<typeof createStepTools<TEvents, TTrigger>>[0];
                                                                   ~

node_modules/inngest/types.d.ts:174:1 - error TS1128: Declaration or statement expected.

174 };
    ~


Found 6 errors.

error Command failed with exit code 2.
```

**System info:**

- OS: Mac
- npm package Version 1.5.1
- Framework Express
- Platform Netlify

**Comment by jpwilliams** [comment]
Thank you for the report!

We must look into additional integration tests for different TS versions to root these problems out earlier.

Looks like `type-fest` shifted from supporting `>=4.2.4` to `>=4.7.0` in [v3.0.0](https://github.com/sindresorhus/type-fest/releases/tag/v3.0.0). The errors in our files should be resolved by providing some parenthesis around the `typeof` call.

A couple of actions from this:

- [ ] Be explicit about TS support via `peerDependencies` and  [`typesVersions`](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions)
- [ ] Add CI tests for specific TS versions to CI, used to fix existing issues documented above

Out of interest, @mahdavipanah, is there a reason you haven't upgraded past `4.4.3`?

**Comment by jpwilliams** [comment]
Started looking at TS CI tests in #151.

We do make heavy use of [instantiation expressions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#instantiation-expressions) that were released in [TS 4.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html), so supporting earlier than that might include some lengthy rewrites. 🤔

**Comment by mahdavipanah** [comment]
> @mahdavipanah We've set the minimum TypeScript version to `4.7` in #151.
> 
> We may be able to provide support for earlier versions in the future, though we use many of the large inference improvements made in 4.7 to provide good typing throughout the library.
> 
> Going to close as I haven't heard back in a bit, but please reach out if you'd like any help upgrading to 4.7+!

Thank you for the clarification. We have updated our project's typescript and are using Inngest's package. Thank you for the help.

**Comment by jpwilliams** [comment]
@mahdavipanah Really glad to hear it! <3
