### ISSUE TITLE
`inngest/next` `serve` Type instantiation is excessively deep and possibly infinite. (ts-2589)

### ISSUE THREAD

**Issue by grempe** [inngest/inngest-js#153]
I am working on an integration in a TypeScript  Next.js app.

I've started to see the following error on the `inngest/next` `serve` function:

![Screen Shot 2023-03-21 at 15 23 55 PM](https://user-images.githubusercontent.com/117/226719640-ee704412-4d13-4be3-86bc-ec9180e906dd.png)

I tried removing the functions one-by-one and the error only goes away when I remove all of them.

Using:

https://github.com/inngest/inngest/releases/tag/v0.11.0
https://github.com/inngest/inngest-js/releases/tag/v1.4.1

I tried reverting to 1.4.0 and still same result.  Now using latest 1.4.1

At the moment I have to rely on `//@ts-expect-error` to allow me to compile.

Thoughts?

**Comment by jpwilliams** [comment]
@grempe I'm struggling to get an immediate reproduction with those versions. 🙁 Could you share any event types you're using and the functions you're serving too?

**Comment by grempe** [comment]
I just went back to look through my report and it seems I failed to submit a critical piece of info that I wrote up and thought I sent. Apologies. 

The thing that triggered this I discovered was a type derived from the Zod example for Json types. 

https://zod.dev/?id=json-type

If the derived typescript type for this is included as the type of an inngest attribute thats when it gave the type errors. 

I've been using this type in a number of other contexts with no issue.

**Comment by jpwilliams** [comment]
Aha - awesome! Thanks for this, @grempe.

Have a fix at #154 - will shout again here when it's released.

**Comment by jpwilliams** [comment]
@grempe Should be fixed in [v1.5.2](https://github.com/inngest/inngest-js/releases/tag/v1.5.2) 🙂

**Comment by grempe** [comment]
Excellent!  I'll give it a go. Thanks for the speedy resolution.

🚀 🥳

**Comment by grempe** [comment]
Confirmed resolved with new release.
