### ISSUE TITLE
Documentation: Add documentation surrounding step.sendEvent and other async operations

### ISSUE THREAD

**Issue by Amethystix** [inngest/inngest-js#164]
Hi! Just had a small request for a documentation update:

https://www.inngest.com/docs/guides/fan-out-jobs In the fan out jobs documentation, it isn't stated that to use `step.sendEvent`, all other asynchronous operations must be wrapped in a `step.run`. Would love to just see some clear wording around this so others don't get confused when `step.send` doesn't work in their jobs- I saw another user have the same problem after I did on Discord, so think this would be worthwhile:

My discord thread: 
https://discord.com/channels/842170679536517141/845000011040555018/1090805866187468862

Other user having the same issue:
https://discord.com/channels/842170679536517141/1093066335023550467/1093066335023550467

This might not be the right place to open a doc issue, please feel free to triage accordingly. I simply opened this here since I'm using the JS SDK

**Comment by jpwilliams** [comment]
Documented now! :)
