### ISSUE TITLE
[BUG] NonRetriableError triggers retry

### ISSUE THREAD

**Issue by dddenis** [inngest/inngest-js#209]
**Describe the bug**
The step is retried when the `NonRetriableError` was thrown.

**To Reproduce**
1. Create a function, which throws `NonRetriableError` inside the `step.run`:
```ts
const test = inngest.createFunction(
  { name: "Test" },
  { event: "test" },
  async ({ step }) => {
    await step.run("test", () => {
      throw new NonRetriableError("Should not retry");
    });
  }
);
```
2. Send test event:
```sh
curl -v -d '{"name":"test","data":{}}' http://localhost:8288/e/test
```

**Expected behavior**
The step is not retried.

**Code snippets / Logs / Screenshots**
Repo with reproduction case: https://github.com/dddenis/inngest-non-retriable-error

**System info (please complete the following information):**

- OS: Mac
- npm package Version: 1.9.3
- Framework: Next.js
- Platform: Vercel

**Comment by jpwilliams** [comment]
Thanks for reporting, @dddenis!

This should be fixed and release in [v1.9.4](https://github.com/inngest/inngest-js/releases/tag/v1.9.4).
