### ISSUE TITLE
Add logger parameter to onFailure

### ISSUE THREAD

**Issue by aabedraba** [inngest/inngest-js#279]
With normal functions I'm using the `logger` this way: 

```ts
 async ({ event, step, logger }) => {
    await step.run("Trigger task", async () => {
      try {
        return await task()
      } catch (err) {
        logger.error("Step Trigger upload event failed: ", {
          userId: event.data.userId
        });
        throw err;
      }
    });
}
```

Nevertheless, I don't get a `logger` on the onFailure section as it's not available, so I would need to do my error handling differently in different places, which is not ideal. 

Is there a reason it was designed this way? Would be great to have it!

**Comment by jpwilliams** [comment]
Thanks for catching this, @aabedraba! Will be fixed in the next release:

- #275
