### ISSUE TITLE
[Feature] Replace zod with typeschema for a less opinionated api

### ISSUE THREAD

**Issue by riordanpawley** [inngest/inngest-js#353]
**Is your feature request related to a problem? Please describe.**
I don’t use zod but I do use a schema library. It shouldn’t matter which one.

**Describe the solution you'd like**
I want to get typeschema into the inngest api before the potential changes proposed by Theo bake zod in further. (I like what I saw in that video btw)
https://github.com/decs/typeschema

**Describe alternatives you've considered**
Just using the types with inngest EventSchema - works for now but…

**Comment by jpwilliams** [comment]
Hi, @riordanpawley! 👋

Thanks for this. We definitely want the types to feel open-ended, hence having our `EventSchemas` class for stacking them and providing them from different sources. We also want to make sure we're not tighly coupled with any one library (or worse, a particular version of a library - see #350).

We're looking at pretty ways to define event types centrally, most likely allowing co-locating with a function but encouraging separating them out as your usage grows. Right now this is just our `EventSchemas` class which can feel a bit clunky, as well as some annoyances around allowing users to type multiple fields (`data`, `user`, `name` transforms, etc.) in a single schema.

We're playing at the moment with encouraging serialized types (read: not pure TS types) which allows a much greater scope of freedom, especially for projects like this.

[decs/typeschema](https://github.com/decs/typeschema) looks like a great project that would take some of the custom shims we're writing off our hands! I'd love to know how it would deal with incompatible minor versions when validating. Even if it doesn't, this would be a nice problem to work on open source anyway.

**Comment by riordanpawley** [comment]
> We're playing at the moment with encouraging serialized types (read: not pure TS types) which allows a much greater scope of freedom, especially for projects like this.

Serialized types as in types that can be sent over network with usecase of something like: https://docs.confluent.io/platform/current/schema-registry/index.html ?

> [decs/typeschema](https://github.com/decs/typeschema) looks like a great project that would take some of the custom shims we're writing off our hands! I'd love to know how it would deal with incompatible minor versions when validating. Even if it doesn't, this would be a nice problem to work on open source anyway.

I'm not sure what the deal with versioning is going to be but I think if it needs work its probably better done in the typeschema library than starting from scratch :)

**Comment by jpwilliams** [comment]
Won't be actioning this yet. Whenever we want to add more of these projects we'll likely first reach for a `.from*()` method on `EventSchemas`.

Keeping an eye on adoption of [decs/typeschema](https://github.com/decs/typeschema) though and will re-open this if we consider it again!

Thank you!
