### ISSUE TITLE
Switch `inngestRegisterUrl` to just `inngestAPI`

### ISSUE THREAD

**Issue by djfarrelly** [inngest/inngest-js#38]
**Is your feature request related to a problem? Please describe.**
Requiring a user to add the `/fn/register` should be unnecessary as every Inngest environment should have this same url. 
https://github.com/inngest/inngest-js/blob/fdea3effd9ef6ed633b2d293ba374ce9235d5a34/src/types.ts#L188-L192

**Describe the solution you'd like**
We should make this simpler by simple passing the URL of the API itself and the SDK can append the path.

**Describe alternatives you've considered**
n/a - this is mostly an internal use case right now, but may grow with more advanced dev server usage and preview environment support.

**Additional context**
n/a

**Comment by MarkMurphy** [comment]
Just pointing out that this can be accomplished already via the env. If the `inngestRegisterUrl` was omitted the register method will look for `INNGEST_DEVSERVER_URL` in the environment and append the `/fn/register` path to it.

https://github.com/inngest/inngest-js/blob/main/src/components/InngestCommHandler.ts#L736

and

https://github.com/inngest/inngest-js/blob/main/src/components/InngestCommHandler.ts#L986-L993

**Comment by jpwilliams** [comment]
These environment variables were revisited in #294.

See https://www.inngest.com/docs/sdk/environment-variables for the latest.
