### ISSUE TITLE
Adding Nest.JS example with dependecy injection

### ISSUE THREAD

**Issue by anasabdullahysfzai** [inngest/inngest-js#380]
**Is your feature request related to a problem? Please describe.**
Recently i was configuring inngest with Nest.js  and all things went well until i wanted to inject a dependency inside inngest function. After searching on internet , i didnt find any solution for this problem.

**Describe the solution you'd like**
I came up with my own solution to inject dependencies inside the function. Now i want to add it as part of examples within the repositories so that its easy for people to get the direction in future.

**Comment by jpwilliams** [comment]
Hi, @anasabdullahysfzai 👋

This would be great to add as an example here! We have [inngest/sdk-example-nestjs](https://github.com/inngest/sdk-example-nestjs) but it's a little outdated now.

Would love a PR to add this - there's a section to help create examples in this repo's [`CONTRIBUTING.md`](https://github.com/inngest/inngest-js/blob/d71c8623679f08ee91c9b094b01ffb709aaa1c9d/packages/inngest/CONTRIBUTING.md#examples).

**Comment by anasabdullahysfzai** [comment]
hey @jpwilliams 
I would create the PR , thanks

**Comment by jpwilliams** [comment]
Created and merged in #387. Thanks, @anasabdullahysfzai!
