### ISSUE TITLE
[Feature] Inngest client & functions should provide the request object & env variables

### ISSUE THREAD

**Issue by ShravanSunder** [inngest/inngest-js#383]
**Is your feature request related to a problem? Please describe.**
Inngest client & functions should provide the request object & env variables
- This would help us access cloudflare resources that are passed in through the request ctx.  https://discord.com/channels/842170679536517141/1171064362044248154/1171102364850192405
- We need env variables for various service bindings in workers, such as accessing KV or durable objects

**Describe the solution you'd like**
Provide the request object and env variables in inngest ctx so that we could use them or create our own middleware

**Describe alternatives you've considered**
As a workaround i'm using globals for cloudflare resource bindings.  This is NOT recommended due to the way workers are isolated.

**Additional context**
Please see https://discord.com/channels/842170679536517141/1171064362044248154/1171102364850192405 

cc: @jpwilliams

**Comment by jpwilliams** [comment]
@ShravanSunder - Added in [v3.9.0](https://github.com/inngest/inngest-js/blob/main/packages/inngest/CHANGELOG.md#390).

See the [Cloudflare Workers AI middleware example](https://www.inngest.com/docs/reference/middleware/examples#cloudflare-workers-ai). 🙂
