### ISSUE TITLE
Allow users to create custom retry policies when defining individual steps

### ISSUE THREAD

**Issue by tonyhb** [inngest/inngest-js#40]
We need to return the retry policy on error so that the executor can update and infer the retry policy when scheduling the next attempt.

A question:  what if there's an irrecoverable error (eg. segfault)?  How do we know the policy at this point?

We may have to change the SDK to reply with an "intent" to run a step only if options are provided, along with additional step config (eg. retries) which are then applied to any attempt

**Comment by jpwilliams** [comment]
This will be closed with #45.

**Comment by jpwilliams** [comment]
Will track this elsewhere. The API has space for this now.
