### ISSUE TITLE
[Feature] Validate event data against zod schema 

### ISSUE THREAD

**Issue by elbalexandre** [inngest/inngest-js#410]
**Is your feature request related to a problem? Please describe.**
Event data is not validated against Zod schemas used for defining Inngest client event schemas.

**Describe the solution you'd like**
When Zod schemas are used, the `send()` function should validate the provided data against the corresponding Zod schema.

**Describe alternatives you've considered**
An alternative could be to remove `EventSchemas.fromZod`. This might be less ambiguous, as users familiar with Zod know they can use z.infer.

**Additional context**
N/A

**Comment by mattddean** [comment]
Agreed, my assumption was that if I was providing a zod schema, the data was being validated.

**Comment by jpwilliams** [comment]
There's a preliminary PR for this over at #657. Leaving this issue open to continue to gather feedback, but you can use that PR to get going now if you need this before we add a first-party option. 🙂

**Comment by arthberman** [comment]
Any update to a better implementation of this instead of using the experimental middleware ?

**Comment by jpwilliams** [comment]
@arthberman We now have a shipped `@inngest/middleware-validation` package that provides this. The plan is to add this as default behaviour in v4 without middleware. 🙂 

- npm: [`@inngest/middleware-validation`](https://www.npmjs.com/package/@inngest/middleware-validation)
- jsr: [`@inngest/middleware-validation`](https://jsr.io/@inngest/middleware-validation)
- GitHub: [`packages/middleware-validation/`](https://github.com/inngest/inngest-js/tree/main/packages/middleware-validation)

cc @mattddean @elbalexandre
