### ISSUE TITLE
[BUG] `id` field is missing from the type definition of `EventPayload`

### ISSUE THREAD

**Issue by fnimick** [inngest/inngest-js#423]
**Describe the bug**
The optional `id` field for idempotent event processing is not defined in the `EventPayload` interface and therefore provides no type checking / editor integration.

see: https://github.com/inngest/inngest-js/blob/main/packages/inngest/src/types.ts#L305

docs: https://www.inngest.com/docs/reference/events/send#inngest-send-event-payload-event-payload-promise

**Comment by jpwilliams** [comment]
@fnimick This is fixed in [`inngest@3.7.2`](https://github.com/inngest/inngest-js/pull/429) 🙂 Thanks for reporting!
