### ISSUE TITLE
[BUG] @inngest/middleware-encryption doesn't work due to missing dist files

### ISSUE THREAD

**Issue by jessethomson** [inngest/inngest-js#450]
**Describe the bug**
The generated dist files are not included in the published package for the `@inngest/middleware-encryption` npm package.

**To Reproduce**

Run the following commands in the terminal

1. `mkdir test-dir`
2. `cd test-dir`
3. `npm init -y`
4. `npm i @inngest/middleware-encryption`
5. `ls -la node_modules/@inngest/middleware-encryption`

**Expected behavior**
I expect to see `dist/index.js` and `dist/index.d.ts` files within the `node_modules/@inngest/middleware-encryption` folder

**Code snippets / Logs / Screenshots**

**Local Screenshot**

<img width="247" alt="Screenshot 2024-01-03 at 8 56 10 PM" src="https://github.com/inngest/inngest-js/assets/15367855/3eee7349-8728-4dee-a9cd-9727d6be3635">

**Unpkg URL**

https://unpkg.com/@inngest/middleware-encryption@0.1.2/dist/index.js

**System info (please complete the following information):**

- OS: MacOS Sonoma 14.1.2
- npm package Version: @inngest/middleware-encryption@0.1.2
- Framework: NextJS
- Platform: AWS (ECS Cluster with Task on Fargate)

**Additional context**
I git cloned the `inngest-js` repo, ran `pnpm install`, and then `pnpm run build`, and everything seems to be generated in the `dist` folder correctly, so my guess is something wrong with the CI or publishing scripts?

**Comment by jessethomson** [comment]
Of course as soon as I create this issue, I find the answer 🤦 

It looks like the issue was already fixed by [this PR](https://github.com/inngest/inngest-js/pull/444), but a changeset still needs to be added for the `@inngest/middleware-encryption` package, and then it needs to be released.

**Comment by jessethomson** [comment]
I created a [quick PR](https://github.com/inngest/inngest-js/pull/451) to fix this, but I also realize:

1) it's so simple it might be easier to do it yourselves
2) You may have conventions I'm not aware of and teaching me isn't a priority (also, see point 1 above)
3) You may not be accepting open source contributions at this time

Anyway, feel free to merge or close according to your preference!

**Comment by jpwilliams** [comment]
Nope, this is perfect, @jessethomson - thanks! I didn't make the connection that this'd be affecting `@inngest/middleware-encryption` too. 🙂

Should be resolved now in [@inngest/middleware-encryption@0.1.3](https://www.npmjs.com/package/@inngest/middleware-encryption/v/0.1.3?activeTab=code).

**Comment by jessethomson** [comment]
Everything looks good in [@inngest/middleware-encryption@0.1.3](https://www.npmjs.com/package/@inngest/middleware-encryption/v/0.1.3?activeTab=code)!

I was able to install it, set it up, and deploy to production and everything seems to be working as advertised! Thanks!
