### ISSUE TITLE
[BUG] The return type of `step.run` is typed incorrectly. It removes object keys with type `unknown`

### ISSUE THREAD

**Issue by anirudhsama** [inngest/inngest-js#456]
**Describe the bug**
The return type of `step.run` is typed incorrectly. It removes object keys with type `unknown`

**To Reproduce**
Consider this function:

```ts
export const helloWorld = inngest.createFunction(
	{ id: "hello-world" },
	{ event: "test/hello.world" },
	async ({  step }) => {
		await step.sleep("wait-a-moment", "1s");
		
		const result = await step.run("do-some-work", () => {
			const d: unknown = { hello: "world" };
			const r = { status: "success", data: d }
			return r;
			// typed as {status: string; data: unknown}
		});

		return result;
		// typed as {status: string}
               // key data is removed
	},
);
```

**Expected behavior**
The return type of `step.run` shouldn't remove unknown keys.

**Code snippets / Logs / Screenshots**

![CleanShot 2024-01-11 at 11 26 23@2x](https://github.com/inngest/inngest-js/assets/832760/20ae04db-a524-4c6d-8694-8c9d32e842bd)

**System info (please complete the following information):**

- OS: Mac
- Inngest 3.7.3
- Framework Next.js
- Platform Vercel

**Comment by jpwilliams** [comment]
Thanks for the report, @anirudhsama!

This should now be fixed in [v3.15.5](https://github.com/inngest/inngest-js/releases/tag/inngest%403.15.5). 🙂
