### ISSUE TITLE
Improve testing experience

### ISSUE THREAD

**Issue by MonsterDeveloper** [inngest/inngest-js#468]
**Is your feature request related to a problem? Please describe.**
Setting up unit tests for Inngest functions is currently challenging due to a lack of guidelines in the official documentation. Exporting from `inngest.createFunction` requires exporting both the function itself and the function passed to it for testing.

**Describe the solution you'd like**
Enable the manual execution of declared functions. For example:
```ts
export const myFunction = inngest.createFunction(...)

myFunction.run()
```
Additionally, include testing guidelines in the docs with practical examples.

**Describe alternatives you've considered**
Exporting the handler callbacks passed into `inngest.createFunction` and testing them using mock objects.

**Comment by brijmcq** [comment]
Would it be possible to expose the test helpers?

**Comment by jpwilliams** [comment]
It's a mentioned issue, but commenting to highlight it.

@MonsterDeveloper just exposed `InngestFunction#createExecution()` over at #618, released in [3.19.16](https://github.com/inngest/inngest-js/pull/621).

Note that it's an internal method that can still change at any time; we'll add first-party testing tooling at a later date, but for now `createExecution()` is indeed what we use for a lot of our internal unit tests.

**Comment by MonsterDeveloper** [comment]
Yep, now it's *possible* to test functions as follows. But beware that it's unstable and is subject to change without notice.

![CleanShot 2024-06-18 at 21 33 42@2x](https://github.com/inngest/inngest-js/assets/16190582/4295cf33-f68f-45e8-a724-fd221ddf498c)

**Comment by jpwilliams** [comment]
Please see inngest/inngest#1680 for further conversation and progress on this. 🙂

- inngest/inngest#1680

**Comment by jpwilliams** [comment]
[@inngest/test](https://github.com/inngest/inngest-js/tree/main/packages/test) is now available to provide some of these options.

Closing this as it was the original discussion around generic testing tools. Please raise issues/PRs against the `@inngest/test` package if you'd like further changes! 🙂
