### ISSUE TITLE
[BUG] Local execution fails with StepRun does not belong to Opcode values after 3.12.0 upgrade

### ISSUE THREAD

**Issue by gwax** [inngest/inngest-js#490]
**Describe the bug**
After upgrading `inngest-js` to `>=3.12.0`, I can no longer run pipelines with `inngest-cli`. Doing so results in the error: `Error: error reading generator opcode response: StepRun does not belong to Opcode values`

**To Reproduce**

1. Take a working configuration with inngest-js <3.12.0 and inngest-cli 0.23.1
2. Upgrade inngest-js to >=3.12.0
3. Start inngest locally
4. Execute a function

**Expected behavior**
Local execution should work as before

**Code snippets / Logs / Screenshots**

**System info (please complete the following information):**

- OS: Mac
- npm package Version: innjest==3.12.0; inngest-cli=0.23.1
- Framework: SvelteKit [e.g. Next.js, Express]
- Platform: Local

**Additional context**

**Comment by jpwilliams** [comment]
Hi, @gwax!

Try it with `inngest-cli@latest`; we usually ship these changes as they move to Cloud, so expect SDKs to work with the latest version.

**Comment by jpwilliams** [comment]
Closing this as I'm expecting no change.

**Comment by gwax** [comment]
Yes, the issue turned out to be an unintentionally pinned older version of inngest-cli; thank you.
