### ISSUE TITLE
More info needed when there's a NESTING_STEPS error

### ISSUE THREAD

**Issue by maktouch** [inngest/inngest-js#546]
**Is your feature request related to a problem? Please describe.**
We've quickly migrated from graphile/worker to inngest. We now have over 160 functions. In my logs, I see "NESTING_STEPS" but there's no info to quickly debug that, as in, what function or step is causing this. 

**Describe the solution you'd like**
I'd love to get the parent function, or the event, or even the step name, so I can go and fix this. 

I can make a PR in this repo if you think it's valid!

**Comment by jpwilliams** [comment]
This is shipped in [`3.18.1`](https://github.com/inngest/inngest-js/releases/tag/inngest%403.18.1) following #549.

Thanks, @maktouch!

I'm also noting https://github.com/inngest/inngest-js/pull/549#issuecomment-2070205258, which highlights how rubbish the stack trace is for this instance: no usable lines and the `prettyError` header/footer have survived. This will be tracked in #531.

![CleanShot 2024-04-22 at 12 47 33](https://github.com/inngest/inngest-js/assets/1134251/bc33c398-0ba8-4c95-8e89-6625e00e3abe)
