### ISSUE TITLE
[BUG] Unmet peer dependency @vercel/node@^2.15.9: found 3.1.6

### ISSUE THREAD

**Issue by david0673** [inngest/inngest-js#603]
**Describe the bug**
Installing the (currently) latest inngest package prints a warning about `Unmet peer dependency @vercel/node@^2.15.9: found 3.1.6`

**To Reproduce**

1. Create a function with '...'
2. Send this event '...'
3. ...

**Expected behavior**

**Code snippets / Logs / Screenshots**
<img width="377" alt="Screenshot 2024-06-07 at 4 16 23 PM" src="https://github.com/inngest/inngest-js/assets/1468812/a5aeea93-f267-43e6-9b3d-5473f926c17e">

**System info (please complete the following information):**

- OS: Mac
- npm package Version 3.19.11
- Framework Next.js
- Platform Vercel

**Comment by jpwilliams** [comment]
Thank you for the report, @david0673! Fixing in #604.
