### ISSUE TITLE
[BUG] Regression between 3.21.0 and 3.21.1

### ISSUE THREAD

**Issue by MatthewAry** [inngest/inngest-js#659]
**Describe the bug**
Event Schema resolution breaks on v3.21.1

**To Reproduce**

1. Using inngest v3.21.1 use the example code found at

https://github.com/inngest/inngest-js/blob/4f80297daa6da9f659f2fc7dae5b713eafa8593c/examples/framework-google-functions-framework/inngest/types.ts

into a properly configured VSCode IDE.

3. Hover over `schemas` to view TS Types.

**Expected behavior**
VSCode should display the variable type as:
```ts
const schemas: EventSchemas<{
    "inngest/function.failed": {
        data: {
            function_id: string;
            run_id: string;
            error: {
                name: string;
                message: string;
                stack: string | undefined;
            };
            event: EventPayload<any>;
        };
        name: "inngest/function.failed";
    };
    "inngest/function.finished": {
        ...;
    };
    "inngest/function.invoked": {
        ...;
    };
    "inngest/scheduled.timer": {
        ...;
    };
    "demo/event.sent": {
        ...;
    };
}>
```

**Actual behavior**
VSCode displays the variable type as:
```ts
const schemas: EventSchemas<any>
```

**Code snippets / Logs / Screenshots**
https://github.com/inngest/inngest-js/blob/4f80297daa6da9f659f2fc7dae5b713eafa8593c/examples/framework-google-functions-framework/inngest/types.ts

**System info (please complete the following information):**

- OS: Mac
- npm package Version 3.21.1
- Framework N/A
- Platform N/A

**Additional context**
This is purely at TS in IDE issue.

**Comment by jpwilliams** [comment]
Thanks for the report, @MatthewAry!

We may have something related at #658, too. I can't yet reproduce either issue, though.
Could I get some more details from you? 🙂 

- Are you reproducing this within the `framework-google-functions-framework` example or just copying code from it?
- What TypeScript version are you using?
- What is the contents of your `tsconfig.json`?

**Comment by MatthewAry** [comment]
Not exclusive to`framework-google-functions-framework` its any kind of Schema you try to define.
Using TS 5.5.3
The complete `tsconfig.json` is hard to extract from my monorepo. The base config is as follows:
```
{
  "$schema": "https://json.schemastore.org/tsconfig.json",
  "compilerOptions": {
    // total-typescript/tsconfig/bundler/no-dom
    /* Base Options: */
    "esModuleInterop": true,
    "skipLibCheck": true,
    "target": "es2022",
    "allowJs": true,
    "resolveJsonModule": true,
    "moduleDetection": "force",
    "isolatedModules": true,
    "verbatimModuleSyntax": true,
    /* Strictness */
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "noImplicitOverride": true,
    /* If NOT transpiling with TypeScript: */
    // "module": "preserve",
    "noEmit": true,

    // Our own changes
    "incremental": true,
    // regarding module/moduleResolution https://x.com/mattpocockuk/status/1724462050288587123?s=20
    "module": "esnext",
    "moduleResolution": "bundler",
    // "composite": true,
    "downlevelIteration": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": ".",
    "noErrorTruncation": true
  },
  "exclude": ["**/node_modules"]
}
```

**Comment by jpwilliams** [comment]
Thanks, @MatthewAry!

Given the change in that patch release, is the `data` of any of the events you're defining ever _not_ an object like `{}`? i.e. `[]`, `null`, etc.

The similar issue in #658 looks like it's caused by specifying `event.data` as an array, which is invalid and will inevitably throw an error at runtime.
