### ISSUE TITLE
Expose event filtering && expressions in SDK

### ISSUE THREAD

**Issue by tonyhb** [inngest/inngest-js#69]
We don't expose expressions on event triggers to users;  this is necessary for users with many events so that they don't have wasted function runs.

**Comment by jpwilliams** [comment]
Parallelism in #45 introduces better config for triggers, e.g.
```ts
// Any type of function uses the same method.
// declare createFunction: (nameOrFunctionOpts, eventNameOrTriggerOpts, fn) => void;
inngest.createFunction("...", "demo/event.sent", () => {});
inngest.createFunction("...", { event: "demo/event.sent" }, () => {});
inngest.createFunction("...", { cron: "* * * * *" }, () => {});
```
We might have to change this to allow typing for expressions (properties defined in the same object can type based on each other), but this would be a good place for them to go.
