### ISSUE TITLE
[BUG]  Inngest JS with Hono on Deno doesn't SYnc

### ISSUE THREAD

**Issue by NicoCaldo** [inngest/inngest-js#720]
**Describe the bug**
I have deployed the example of the [docs regarding Hono Framework](https://www.inngest.com/docs/learn/serving-inngest-functions#framework-hono) but it won't sync with the local Inngest Server (Docker). If I go to `http://localhost:3000/api/inngest` it returns 

`{"authentication_succeeded":null,"extra":{"is_mode_explicit":false},"has_event_key":false,"has_signing_key":false,"function_count":3,"mode":"dev","schema_version":"2024-05-24"}`

**To Reproduce**

1. Deploy Deno `deno init my_project`
2. Use the example in the Inngest project for the `main.ts` (see code below)
3. Run the [Docker command from Inngest docs](https://www.inngest.com/docs/guides/development-with-docker#standalone-docker-container) for the dev server
4. Run the Hono on Deno server with `deno run --env --watch --allow-net --allow-env main.ts`

**Expected behavior**
The dev server sync with the app

**Code snippets / Logs / Screenshots**
```

import { Hono } from 'npm:hono'
import { serve } from "npm:inngest/hono";
import { functions, inngest } from "./inngest.ts";

const app = new Hono()

app.on(
  ["GET", "PUT", "POST"],
  "/api/inngest",
  serve({
    client: inngest,
    functions,
  })
);

Deno.serve({port: 3000,}, app.fetch)
```

**System info (please complete the following information):**

- OS: Ubuntu 24.04.1 LTS 6.8.0-40-generic
- npm package Version n.a.
- Framework Hono on Deno
- Platform local dev

**Comment by NicoCaldo** [comment]
Closing because the issue seems the Docker image. I'll open another Issue with the details and step to reproduce

**Comment by jgoux** [comment]
@NicoCaldo Did you have it working in the end? I'm stuck with Inngest on Deno as well (using Hono like you). 😢

**Comment by NicoCaldo** [comment]
> @NicoCaldo Did you have it working in the end? I'm also stuck with Inngest on Deno (using Hono like you). 😢

Unfortunately, I've stuck to using Hono on Deno because I've not had time to figure it out. After all, standalone Deno doesn't work.

I think the solution is to somehow integrate the [edge.ts](https://github.com/inngest/inngest-js/blob/main/packages/inngest/src/edge.ts) with Deno2.

About the Dev Server, I ended up to use `npx `on my host machine instead of Docker

**Comment by jgoux** [comment]
I mean, even without Hono, are you able to run Inngest in Deno and have the local server syncing the functions?
