### ISSUE TITLE
[BUG] @inngest/test errors on steps do not throw

### ISSUE THREAD

**Issue by aon** [inngest/inngest-js#732]
**Describe the bug**

Errors on steps don't throw.

**To Reproduce**

- Create any function with steps and send a throw inside a step.

**Comment by jpwilliams** [comment]
Thanks for the report, @aon!

Could you show the version of `@inngest/test` you're using and the code that's causing this?

**Comment by aon** [comment]
Hi! Sorry for the delayed response. I've created a repository to show both this and #731. Let me know if I can help in some other way. https://github.com/aon/inngest-debug-test-package

**Comment by aon** [comment]
Unfortunately this still isn't working. If I create two steps and the second one throws, it doesn't work. I've updated the repo to show this issue. https://github.com/aon/inngest-debug-test-package

**Comment by jpwilliams** [comment]
> Unfortunately this still isn't working. If I create two steps and the second one throws, it doesn't work. I've updated the repo to show this issue. https://github.com/aon/inngest-debug-test-package @jpwilliams

Thanks, @aon!

Further fix: #749.
