### ISSUE TITLE
Throw a clear error when nesting `tools.run`

### ISSUE THREAD

**Issue by tonyhb** [inngest/inngest-js#77]
When nesting `tools.run` the error thrown/visible is `unknown error: {}`:

<img width="508" alt="Screenshot_2023-01-15_at_4 29 17_PM" src="https://user-images.githubusercontent.com/306177/212568603-ed2fe776-5ee5-416f-8e24-2fe6dda3dbcd.png">

We should throw a clear error to make this anti-pattern/unsupported case obvious.

**Comment by jpwilliams** [comment]
This was fixed in #193.
