### ISSUE TITLE
Support Vercel Edge Functions

### ISSUE THREAD

**Issue by DaleLJefferson** [inngest/inngest-js#78]
When using NextJS * Vercel Edge functions `fetch` is not correctly detected.

```
ReferenceError: XMLHttpRequest is not defined
```

Looking at the code https://github.com/inngest/inngest-js/blob/main/src/components/Inngest.ts#L129 it looks like if you don't provide a fetch in the constructor it falls back to using cross-fetch, which I guess thinks the edge functions are a browser and tries to use XMLHttpRequest polyfil.

As a workaround supplying fetch seems to work and I'm able to send events.

```
new Inngest({fetch})
```

**Comment by DaleLJefferson** [comment]
Great to see you are working on this. I'm planning on using inngest in edge and non edge functions if that confuses things.

serve - standard node function NextJS / Vercel
client - node and edge functions NextJS / Vercel

I would suggest that the serve function should be platform specific but the client should work on anywhere by detecting the environment (it should just need fetch I guess). 

```ts
import {serve} from "inngest/nextjs"
// or
import {serve} from "inngest/edge"
```

```ts
// Always
import {Inngest} from "inngest"
```

**Comment by jpwilliams** [comment]
Aye, the client should definitely be environment agnostic.

Will reference this with a PR to fix!

**Comment by DaleLJefferson** [comment]
Thanks for sorting this out ⭐
