### ISSUE TITLE
[BUG] @inngest/test@0.1.4 - module not found 

### ISSUE THREAD

**Issue by ArthurHoaro** [inngest/inngest-js#783]
**Describe the bug**

When upgrading to @inngest/test, the package seems unusable by TS.
The changelog says 

> Altered exports to now be namespaced by ./dist/; if you have directly imported files from @inngest/test, you may need to change the imports

I'm not sure what imports change should be, but with a minor version bump and no documentation change, it's probably not expected to break.

**To Reproduce**

1. `npm install @inngest/test@0.1.4`
2. In a jest TS file `import { InngestTestEngine } from '@inngest/test';`

Error: 

> Cannot find module '@inngest/test' or its corresponding type declarations.ts(2307)

**Expected behavior**

Being able to import the test engine.

**Comment by wyozi** [comment]
@jpwilliams could you also publish @inngest/test again? :) The `latest` tag is broken

**Comment by jpwilliams** [comment]
Sorry about that, @wyozi!

Released in [@inngest/test@0.1.5](https://github.com/inngest/inngest-js/releases/tag/%40inngest%2Ftest%400.1.5) 🙂
