### ISSUE TITLE
Add optional email, external_id, etc. user properties to the event type

### ISSUE THREAD

**Issue by tonyhb** [inngest/inngest-js#87]
We should document the predefined user fields which have first class support as optional TS types.

**Comment by jpwilliams** [comment]
We removed this previously as it would collide with generated types of events that didn't specify these fields.

See 12b2d2e9a281ef47a0213d30f03b854dc4952d01.

Conflicting types are the real issue; we can type that `user.id?: string`, but if an event comes in with `user.id` as a `number`, we break the contract. 🤔
