### ISSUE TITLE
`Inngest#send()` error messages are vague

### ISSUE THREAD

**Issue by jpwilliams** [inngest/inngest-js#94]
## Summary

We have a list of errors thrown by `Inngest#send()` to inform the user that Inngest did not successfully receive their event payload. See [src/components/Inngest.ts#L151](https://github.com/inngest/inngest-js/blob/main/src/components/Inngest.ts#L151).

None of the errors provides helpful information, requiring a user to guess what's wrong.

Let's adjust so that every error message tells a user:

- What happened
- To the best of our ability, why
- Help the user fix the error by mentioning a likely cause
- Provide further steps (relevant docs link) should the likely cause not be the issue

**Comment by djfarrelly** [comment]
Yeah, this is remanent of the original SDK release where the Inngest Event API was not returning any response except for the status code. I believe we have better coverage there, but if we return better errors from the Event API both in open source and in Cloud, we can remove this logic and pass through issues!
